name: Setup Node
description: Sets up the node / javascript environment
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - run: yarn install --frozen-lockfile
      shell: bash
