import './src/global.scss'
import '@fontsource/atkinson-hyperlegible/400.css'
import '@fontsource/atkinson-hyperlegible/700.css'
import '@fontsource/fira-code/400.css'
import '@fontsource/fira-code/700.css'
