minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - devalue@5.6.2 # https://github.com/advisories/GHSA-g2pg-6438-jwpf
  - h3@1.15.5 # https://github.com/advisories/GHSA-mp2g-9vg9-f4cg
  - ufo@1.6.3 # required for h3@1.15.5
  # Renovate security update: lodash-es@4.17.23
  - lodash-es@4.17.23
