name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      # The build generates typescript types that are needed for the typecheck
      # step to pass. We're already building elsewhere so this is a little
      # wasteful but it's better than having the typecheck as part of the build
      # and publish loop IMO.
      - run: yarn build
      - run: yarn typecheck
