name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn build
      - run: tar czvf public.tar.gz public/
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: public.tar.gz
          if-no-files-found: error
  
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn typecheck
  