name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm typecheck

  lint-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm lint:ts

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm format:check

  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --all-systems --keep-going

  nix-format-check:
    name: check .nix files format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: find . -iname '*.nix' -print0 | xargs -0 -t nix develop -c nixpkgs-fmt --check
