name: PR

on:
  pull_request:

jobs:
  publish-draft:
    uses: ./.github/workflows/_build-and-publish.yml
    secrets: inherit
    with:
      netlifyDeployArgs: --alias 'pr-${{ github.event.number }}'
