name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-release:
    uses: ./.github/workflows/_build-and-publish.yml
    secrets: inherit
    with:
      env: production
      netlifyDeployArgs: --prod
